{% set name = "IngeoML" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ingeoml-{{ version }}.tar.gz
  sha256: 05d69b6a7c6f62fd7949a9fc39d28e3a1cedd4f40e5139adebfad5b179d0512e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  noarch: python

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - scikit-learn >=1.3.0
    - python >={{ python_min }}

test:
  imports:
    - IngeoML
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/IngeoML
  summary: Machine Learning Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
